type: "joint_state_controller/JointStateController"
publish_rate: 50

type: "position_controllers/JointPositionController"
joint: wheel_back_right_spin

type: "position_controllers/JointPositionController"
joint: front_wheel_left_steer

