mast:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  front_wheel_right_steer_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_wheel_right_steer
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_wheel_left_steer_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_wheel_left_steer
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel_back_spin_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_spin
    pid: {p: 100.0, i: 0.01, d: 10.0}
